# Generated by Django 3.0 on 2021-02-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('UB', 'Upper Body'), ('LB', 'Lower Body'), ('C', 'Core'), ('FB', 'Full Body'), ('Re', 'Recovery')], max_length=20),
        ),
    ]
