# Generated by Django 3.0 on 2021-02-20 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210218_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', through='api.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
